// <auto-generated />
using System;
using DataLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(TpeduContext))]
    [Migration("20251022164532_AddAttributeForUserEntity")]
    partial class AddAttributeForUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LessonID");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("StudentID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.AvailabilityBlock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TutorID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("AvailabilityBlock", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EducationLevelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Class__CB1927C08608731F");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ClassAssign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("ClassId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassAssign", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevelId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TutorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ClassReq__33A8517A858CC078");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("ClassRequest", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequestSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassRequestId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassRequestId");

                    b.ToTable("ClassRequestSchedule", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.EducationLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Educatio__6F6237CDB26778B5");

                    b.ToTable("EducationLevel", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Feedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("ToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__6A4BEDD6F1A4F2BB");

                    b.HasIndex("FromUserId");

                    b.HasIndex("LessonId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.LearningMaterial", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Learning__C50610F7D00FA71A");

                    b.HasIndex("ClassId");

                    b.ToTable("LearningMaterial", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Media", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TutorProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Media__B2C2B5CF88789472");

                    b.HasIndex("LessonId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TutorProfileId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("DataLayer.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Message__C87C0C9C8E34634D");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__20CF2E120CBDEB29");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ParentProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedStudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Relationship")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__ParentPr__D339516FB6AE405F");

                    b.HasIndex("LinkedStudentId");

                    b.HasIndex("UserId");

                    b.ToTable("ParentProfile", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.RecurringSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ClassID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("RecurringSchedule", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ReporterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TargetLessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Report__D5BD48055AA94599");

                    b.HasIndex("ReporterId");

                    b.HasIndex("TargetLessonId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Role__8AFACE1A59C340B0");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.ScheduleEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlockId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("BlockID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LessonId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LessonID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TutorID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("LessonId");

                    b.HasIndex(new[] { "TutorId", "StartTime" }, "UQ_ScheduleEntry_Tutor_StartTime")
                        .IsUnique();

                    b.ToTable("ScheduleEntry", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.StudentProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreferredSubjects")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__32C52B9926DD24AA");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentProfile", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Subject__AC1BA3A8ED7AD384");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__55433A6BD42E289E");

                    b.HasIndex("WalletId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.TutorProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("ApprovedByAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceDetails")
                        .HasColumnType("text");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvideNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SpecialSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeachingExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("TeachingLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeachingSubjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__TutorPro__77C70FE2F53C4D03");

                    b.HasIndex("UserId");

                    b.ToTable("TutorProfile", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BannedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__User__1788CC4C79B935BF");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105343AB23C97")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Wallet__84D4F90EC6481D7E");

                    b.HasIndex("UserId");

                    b.ToTable("Wallet", (string)null);
                });

            modelBuilder.Entity("DataLayer.Entities.Attendance", b =>
                {
                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Lesson");

                    b.HasOne("DataLayer.Entities.StudentProfile", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_StudentProfile");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataLayer.Entities.AvailabilityBlock", b =>
                {
                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("AvailabilityBlocks")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AvailabilityBlock_TutorProfile");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.Class", b =>
                {
                    b.HasOne("DataLayer.Entities.EducationLevel", "EducationLevel")
                        .WithMany("Classes")
                        .HasForeignKey("EducationLevelId")
                        .HasConstraintName("FK__Class__Education__09A971A2");

                    b.HasOne("DataLayer.Entities.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__Class__SubjectId__08B54D69");

                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("Classes")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK__Class__TutorId__07C12930");

                    b.Navigation("EducationLevel");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassAssign", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("ClassAssigns")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_ClassAssign_Class");

                    b.HasOne("DataLayer.Entities.StudentProfile", "Student")
                        .WithMany("ClassAssigns")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_ClassAssign_StudentProfile");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequest", b =>
                {
                    b.HasOne("DataLayer.Entities.EducationLevel", "EducationLevel")
                        .WithMany("ClassRequests")
                        .HasForeignKey("EducationLevelId");

                    b.HasOne("DataLayer.Entities.StudentProfile", "Student")
                        .WithMany("ClassRequests")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__ClassRequ__Stude__0A9D95DB");

                    b.HasOne("DataLayer.Entities.Subject", "Subject")
                        .WithMany("ClassRequests")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__ClassRequ__Subje__0C85DE4D");

                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("ClassRequests")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK__ClassRequ__Tutor__0B91BA14");

                    b.Navigation("EducationLevel");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequestSchedule", b =>
                {
                    b.HasOne("DataLayer.Entities.ClassRequest", "ClassRequest")
                        .WithMany("ClassRequestSchedules")
                        .HasForeignKey("ClassRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClassRequestSchedule_ClassRequest");

                    b.Navigation("ClassRequest");
                });

            modelBuilder.Entity("DataLayer.Entities.Feedback", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "FromUser")
                        .WithMany("FeedbackFromUsers")
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("FK__Feedback__FromUs__1332DBDC");

                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("Feedbacks")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK__Feedback__Lesson__151B244E");

                    b.HasOne("DataLayer.Entities.User", "ToUser")
                        .WithMany("FeedbackToUsers")
                        .HasForeignKey("ToUserId")
                        .HasConstraintName("FK__Feedback__ToUser__14270015");

                    b.Navigation("FromUser");

                    b.Navigation("Lesson");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("DataLayer.Entities.LearningMaterial", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__LearningM__Class__123EB7A3");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DataLayer.Entities.Lesson", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Lesson_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DataLayer.Entities.Media", b =>
                {
                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("Media")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK__Media__LessonId__114A936A");

                    b.HasOne("DataLayer.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.TutorProfile", "TutorProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("TutorProfileId");

                    b.Navigation("Lesson");

                    b.Navigation("OwnerUser");

                    b.Navigation("TutorProfile");
                });

            modelBuilder.Entity("DataLayer.Entities.Message", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Message__Receive__19DFD96B");

                    b.HasOne("DataLayer.Entities.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Message__SenderI__18EBB532");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DataLayer.Entities.Notification", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__1AD3FDA4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.ParentProfile", b =>
                {
                    b.HasOne("DataLayer.Entities.StudentProfile", "LinkedStudent")
                        .WithMany("ParentProfiles")
                        .HasForeignKey("LinkedStudentId")
                        .HasConstraintName("FK__ParentPro__Linke__05D8E0BE");

                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("ParentProfiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ParentPro__UserI__04E4BC85");

                    b.Navigation("LinkedStudent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.RecurringSchedule", b =>
                {
                    b.HasOne("DataLayer.Entities.Class", "Class")
                        .WithMany("RecurringSchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RecurringSchedule_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DataLayer.Entities.Report", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "Reporter")
                        .WithMany("ReportReporters")
                        .HasForeignKey("ReporterId")
                        .HasConstraintName("FK__Report__Reporter__160F4887");

                    b.HasOne("DataLayer.Entities.Lesson", "TargetLesson")
                        .WithMany("Reports")
                        .HasForeignKey("TargetLessonId")
                        .HasConstraintName("FK__Report__TargetLe__17F790F9");

                    b.HasOne("DataLayer.Entities.User", "TargetUser")
                        .WithMany("ReportTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("FK__Report__TargetUs__17036CC0");

                    b.Navigation("Reporter");

                    b.Navigation("TargetLesson");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("DataLayer.Entities.ScheduleEntry", b =>
                {
                    b.HasOne("DataLayer.Entities.AvailabilityBlock", "Block")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("BlockId")
                        .HasConstraintName("FK_ScheduleEntry_AvailabilityBlock");

                    b.HasOne("DataLayer.Entities.Lesson", "Lesson")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK_ScheduleEntry_Lesson");

                    b.HasOne("DataLayer.Entities.TutorProfile", "Tutor")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleEntry_TutorProfile");

                    b.Navigation("Block");

                    b.Navigation("Lesson");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("DataLayer.Entities.StudentProfile", b =>
                {
                    b.HasOne("DataLayer.Entities.EducationLevel", "EducationLevel")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("EducationLevelId")
                        .HasConstraintName("FK__StudentPr__Educa__03F0984C");

                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__StudentPr__UserI__02FC7413");

                    b.Navigation("EducationLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.Transaction", b =>
                {
                    b.HasOne("DataLayer.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .HasConstraintName("FK__Transacti__Walle__1CBC4616");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DataLayer.Entities.TutorProfile", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("TutorProfiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TutorProf__UserI__06CD04F7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.User", b =>
                {
                    b.HasOne("DataLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleId__02084FDA");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataLayer.Entities.Wallet", b =>
                {
                    b.HasOne("DataLayer.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Wallet__UserId__1BC821DD");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entities.AvailabilityBlock", b =>
                {
                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.Class", b =>
                {
                    b.Navigation("ClassAssigns");

                    b.Navigation("LearningMaterials");

                    b.Navigation("Lessons");

                    b.Navigation("RecurringSchedules");
                });

            modelBuilder.Entity("DataLayer.Entities.ClassRequest", b =>
                {
                    b.Navigation("ClassRequestSchedules");
                });

            modelBuilder.Entity("DataLayer.Entities.EducationLevel", b =>
                {
                    b.Navigation("ClassRequests");

                    b.Navigation("Classes");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("DataLayer.Entities.Lesson", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Feedbacks");

                    b.Navigation("Media");

                    b.Navigation("Reports");

                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataLayer.Entities.StudentProfile", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ClassAssigns");

                    b.Navigation("ClassRequests");

                    b.Navigation("ParentProfiles");
                });

            modelBuilder.Entity("DataLayer.Entities.Subject", b =>
                {
                    b.Navigation("ClassRequests");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("DataLayer.Entities.TutorProfile", b =>
                {
                    b.Navigation("AvailabilityBlocks");

                    b.Navigation("Certificates");

                    b.Navigation("ClassRequests");

                    b.Navigation("Classes");

                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.User", b =>
                {
                    b.Navigation("FeedbackFromUsers");

                    b.Navigation("FeedbackToUsers");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("Notifications");

                    b.Navigation("ParentProfiles");

                    b.Navigation("ReportReporters");

                    b.Navigation("ReportTargetUsers");

                    b.Navigation("StudentProfiles");

                    b.Navigation("TutorProfiles");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("DataLayer.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
